http:
  listener:
    host: "localhost"
    port: "9085"
  requester:
    travelOnTip:
      host: "localhost"
      port: "9083"
      routesPath: "/travelOnTipCall/routes"
      schedulesPath: "/travelOnTipCall/schedules"
    fastGo:
      host: "localhost"
      port: "9084"
      routesPath: "/fastGoCall/routes"
      schedulesPath: "/fastGoCall/schedules"
     
    
  